ALTER TABLE signatures
  ADD COLUMN pdf_id INT,
  ADD COLUMN x VARCHAR(255),
  ADD COLUMN y VARCHAR(255),
  ADD COLUMN w VARCHAR(255),
  ADD COLUMN h VARCHAR(255),
  ADD COLUMN page VARCHAR(255),
  ADD FOREIGN KEY (pdf_id) REFERENCES pdfs(id);

