DELETE FROM file_categories WHERE category IN
    ('PROPERTY_PURCHASE_CONTRACT',
    'RESERVATION_FEE',
    'DEPOSIT',
    'COMPLETION_STATEMENT',
    'MORTGAGE_STATEMENT',
    'OFFER_LETTER',
    'REFINANCE_MORTGAGE_STATEMENTS',
    'RENTAL_STATEMENT',
    'MANAGEMENT_LETTING_AGREEMENT');