name: Go

on:
  push:
    branches: [ main ]
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    environment:
       name: ${{ github.ref_name }}
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
    steps:
    - uses: actions/checkout@v3

    - name: set up go environment
      uses: actions/setup-go@v3
      with:
        go-version: 1.17.8

    - name: set up job environment
      run: |
        echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
        echo "${GOPATH}/bin" >> $GITHUB_PATH
        echo "${{ github.ref_name }}"
      shell: bash

    - name: set up goose
      run: |
        go version
        go install github.com/pressly/goose/v3/cmd/goose@latest

    - name: goose - test instalation
      run: goose -version

    - name: goose - fix migration numbers
      run: goose -dir migrations fix

    - name: goose - apply migrations
      run: goose -dir migrations mysql "$DB_USER:DB_PASSWORD@tcp($DB_HOST:$DB_PORT)/$DB_NAME?parseTime=true" up